meta:
  title: "Jeff Anders"
  description: "Co-Founder of Ambrook. Previously design at Scale AI, Facebook, Minimill, Autodesk, and Venmo. Alum of Maryland. I like making cool things with cool people."
  facebook_image: "/img/jeffanders-background.jpg"
  twitter_image: "/img/jeffanders-background.jpg"
  image: "/img/jeffanders-background.jpg"
  twitter_handle: "@jeffand_"
  domain: "jeffanders.co"
  root: "https://jeffanders.co"
  google_analytics_id: "UA-46817894-1"

name: "Jeff Anders"
markdown: kramdown
highlighter: pygments
permalink: "/:title/"
url: "https://jeffanders.co" # the base hostname & protocol for your site

# Jekyll Picture Tag
picture:
  source: img/

# Build info
incremental: true
plugins:
  - jekyll-redirect-from

include:
  - _redirects

exclude:
  - node_modules
  - Gulpfile.js
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - LICENSE.md
  - yarn.lock
